server:
  port: ${SERVER_PORT}
  error:
    include-message: always
    include-binding-errors: never
    include-stacktrace: never
    include-exception: false

logging:
  level:
    web: INFO

spring:
  beaninfo:
    ignore: true
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://${DATABASE_HOST}:${DATABASE_PORT}/${DATABASE_NAME}
    username: ${DATABASE_USERNAME}
    password: ${DATABASE_PASSWORD}
  flyway:
    enabled: true
    table: migration
    create-schemas: true
  jpa:
    open-in-view:
  main:
    banner-mode: off
    allow-bean-definition-overriding: true
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
